### ISSUE TITLE
"Mature" package management with a two-month-old tool?

### ISSUE THREAD

**Issue by Blaisorblade** [Gabriel439/post-rfc#34]
Stack looks really cool, and much better than `cabal-install`, but it's too young to make an area "mature" — indeed, I run into a bug within 5 commands (commercialhaskell/stack#665).

In other mature areas, "mature" is used as I'd expect: tools/libraries are old enough to be (next to) bug-free (say QuickCheck).

(Maybe package management is mature according to the definition you give, but then I disagree with the definition/the terminology/the lack of intermediate degrees).

**Comment by Gabriella439** [comment]
I ran into the same bug before I even wrote the post, but I still think `stack` warrants a "mature" rating.

I don't really view age to be an accurate measure of being bug free.  `cabal` is probably the best example of this within the Haskell ecosystem.  There are also many examples of pretty low quality build tools in other mainstream languages (basically, all of them).  You could make an argument that perhaps "Mature" is the wrong term to use, then, but I was pretty clear about defining what I meant each ranking to mean at the beginning of the post.

Heck, even the venerable `make`, which would probably be as "mature" as you're going to get by your definition still has major outstanding bugs.  The foremost bug in my mind being how terrible [Recursive Make](http://aegis.sourceforge.net/auug97.pdf) is, but there is also a longer list of unresolved bugs [here](http://savannah.gnu.org/bugs/?group=make).

I've used the `stack` tool long enough in my personal projects that I feel confident enough in saying that it is as good most other build tools.  It has some deficiencies compared to other build tools (like the bug you linked, which was immediately fixed by the way), but it also has some strengths that counterbalance those deficiencies.  I believe the strengths of the tool (particularly the use of Stackage to eliminate build failures at compile time) more than make up for the few deficiencies.  Additionally, `stack` is commercially backed by FPComplete with paid developers improving the tool and fixing bugs fulltime, so I expect that the situation will only continue to improve.

**Comment by GetContented** [comment]
On the other hand, it's STILL incredibly annoying and difficult to use for a non-expert. Granted, not compared to cabal, but if you compare it to something like brew, npm, leiningen or bundler, it's really not that great to use.

By the way, I think you should improve the definitions of your "levels" at the beginning of the document. "Acceptable for most programmers" doesn't mean as much as "Can be used by beginning Haskellers" or "Can be used by complete novices". The levels don't appear to be on the same grading criteria, hence it'd probably be recommended to say a bit more about what each means.

**Comment by alexanderkjeldaas** [comment]
I don't get this criticism.  `stack install foo` is as painless as `brew`.  `npm` is guaranteed to install something that breaks down the line, unlike `stack`. I haven't used leiningen or bundler.

**Comment by cdupont** [comment]
stack is quite mature and used, I think this can be closed...

**Comment by Blaisorblade** [comment]
It makes sense to agree to disagree at this point. Closing.

**Comment by GetContented** [comment]
The definition "mature" is here used to mean a quality level not a time duration.
