### ISSUE TITLE
Chart examples

### ISSUE THREAD

**Issue by timbod7** [Gabriel439/post-rfc#35]
Nice Document!

But...

> To pick on one library as an example, the Chart library does not have a single minimal end-to-end code example that I can find anywhere in the Hackage documentation. 

Whilst the Chart library is a long way from perfect. I don't really understand this criticism. The wiki (https://github.com/timbod7/haskell-chart/wiki, referenced from hackage) has a dozen or so examples of working code.

**Comment by Gabriella439** [comment]
So I think the issue here is that the Chart package doesn't mention the Github examples anywhere in the Haddock documentation.  I was going to open up a ticket to fix this but then I realized that you are the maintainer of `Chart` :)

Maybe this would be as simple as adding one complete example in the description of `Chart` and then a link pointing to the remaining Github examples.

**Comment by timbod7** [comment]
I will do that.

I had assumed that most people would find the examples on the wiki, but evidently that is not the case:-)

**Comment by Gabriella439** [comment]
Thanks!  Also let me know when this is fixed so I can update the post

**Comment by timbod7** [comment]
Done: https://hackage.haskell.org/package/Chart-1.5.3/docs/Graphics-Rendering-Chart-Easy.html

I actually forgot the extra link back to the wiki -  I've comitted the change and it will go to hackage in the next update.
