### ISSUE TITLE
Incremental Development

### ISSUE THREAD

**Issue by ExternalReality** [Gabriel439/post-rfc#39]
Hello Gabriel. About the same time that I stumbled upon Haskell I was also being taught the practice of incremental development techniques (TDD and so forth). Haskell's type system in general, partial type signatures, type holes, mature testing, purity, and laziness, make the Haskell experience, IMHO,  "Best In Class" in the  Incremental Development category. Incremental development is a popular topic and perhaps it deserves a section in this fine article.

**Comment by Gabriella439** [comment]
Do you have a post I could read on this style of Haskell programming?

**Comment by ExternalReality** [comment]
@Gabriel439 No, I don't actually know of an article addressing this head on. However, I can provide some links that taken together present the concept.
- http://www.jamesshore.com/Blog/Red-Green-Refactor.html 
- http://codinguncut.com/ocr-text-recognition-data-driven-programming/
- http://matthew.brecknell.net/post/hole-driven-haskell/

The first link is basically the concept and the subsequent links describes how some approach it in Haskell. The reason I propose a section on this is that the technique of incrementally building up programs by heavily relying short cycles of coding and querying the programming environment (types, tests) is quite popular in many programming communities and yet it is relatively unknown that the features of Haskell greatly facilitate this style of programming.

**Comment by GetContented** [comment]
@Gabriel439 If you google TDD, BDD or Hole Driven Development you'll find many references to it. It's very common in OOP circles. Basically, you use the compiler or test runner to tell you what to do next. Personally I don't like it much because it potentially can divorce the coder from being required to have an understanding of what they're doing.

Another way to put this is constraints based programming. You set up the constraints of your requirements in advance (with Cucumber, or quick-check, or just by writing tests in an x-Unit framework), and then you simply fill in the code that achieves that aim. When we write the type signature of a function before creating the function we're effectively doing this: "I want the function that satisfies this type", etc.

One of the other troubles with it is when your "top down view" of the way things should work is actually incorrect - you have to flip back to the top level while you're in the middle of trying to make the bottom level function. It can get messy. Having said this, a lot of folk love it, because it's a simple rule that can help you to think about your code. In Haskell, we pretty much have the type system to do this for us, though.

**Comment by Gabriella439** [comment]
How about this:
- I rename the "Types" section to "Types / Type-driven development"
- I add a paragraph to that section talking about this rough concept and type-holes and partial type signatures

That will at least get the phrase "Type driven development" out there and in people's minds so they can start connecting the dots.  I view this concept as being heavily related to the "Types" section in general, which is why I would prefer to group the two.

**Comment by ExternalReality** [comment]
@GetContented That was a nice overview indeed. 

@Gabriel439 I think your proposal is good! Its only ashamed that many who do value the technique that @GetContented described are scarcely aware that it is a category for which Haskell excels. I think that this  blurb about it will help some. Great!

**Comment by alanz** [comment]
Just a note: `hspec` is basically a haskell version of Ruby's `spec`, which is a tool all about TDD/BDD

**Comment by Gabriella439** [comment]
Alright, here is what I added: https://github.com/Gabriel439/post-rfc/commit/3e433cbbdd514422dc6021a16269125a129b3193

Take a look at that and see if that looks okay

**Comment by GetContented** [comment]
:+1:

**Comment by jpvillaisaza** [comment]
:+1:

**Comment by Gabriella439** [comment]
I'll go ahead and mark this resolved, then.  Feel free to reopen this if you would like to suggest any other changes, though.
