### ISSUE TITLE
http://happylearnhaskelltutorial.com

### ISSUE THREAD

**Issue by GetContented** [Gabriel439/post-rfc#64]
I wonder if you'd consider adding this resource (and maybe mentioning on your blog, too!)

:)

**Comment by Gabriella439** [comment]
The URL is currently broken for some reason

**Comment by GetContented** [comment]
Sorry it needs wwws. http://www.happylearnhaskelltutorial.com

It's supposed to redirect from http://happylearnhaskelltutorial.com but it isn't. I'll look at fixing that.

**Comment by GetContented** [comment]
Ok the DNS redirecting is fixed now as well. :)

**Comment by Gabriella439** [comment]
I'm still reluctant to add this, mainly because I feel that it's not a "best in class" resource.  I feel like the "Haskell Programming from first principles" book and the "Haskell wikibook" are probably better alternatives.

**Comment by GetContented** [comment]
My understanding of the SOTU is that it's "the current state of play" not just "best in class".

Which other guides are there with a similar philosophy? for the absolute beginner that explain the basics with the aide of pictures and that break things down into a reading phase before a writing phase?

You could probably site LYAH, except that it isn't for the absolute beginner. Its examples are small and out of a larger context, and it has quite a few points that leave learners scratching their heads, or falling asleep because of the way it's constructed/written.

While it's understandable that you feel this isn't best in class, it's written to fill a gap: the absolute beginner that doesn't have the drive to sit through large amounts of text, and who likes to leasn in smaller chunks.

Could you provide some pointers as to where it falls down in your opinion, and why?

We're obviously failry biased here, because we wrote it for these reasons :)

**Comment by Gabriella439** [comment]
Sorry for the delay in answering.  I may still add it, but I just need more time to think about this.  I've just been busy with paternity leave :)

**Comment by GetContented** [comment]
No problem! We're very much interested in improving it. So far you're one of two people who have told us it's not great, but not explained how. This is fine and all, but it doesn't let us improve it very easily. (There are quite a few improvements we'd like to do and obviously it's Vol 1 in a series, but we can't continue to write more without more of the community purchasing it, so it's been interesting)

Something that might not be obvious is that this volume only gets as far as _writing_ a simple what's your name? kind of program. We're taking a different approach to other manuals and books: that reading and writing should be done in staged lock-step (writing after reading) and that trying to tackle them both together is a bad idea.

We feel what the beginner needs is _solid practice_ in reading and then writing. It's a bit tricky to just throw the reader in at the deep end of reading full real programs straight away, so we get them to read "beginner" programs instead. For example, in Chapters 16, 18 & 19 there are some text-based games. These use a simple recursive mechanism passing a state variable back. If this were to be done properly, they should be using the State monad, but at this point the learner hasn't seen Monad yet even in reading, so we haven't done it that way.

But yeah, we'd be very interested in your feedback, if possible. We know it's a lot of work.

Congrats on the baby! :)

**Comment by Gabriella439** [comment]
There are some good parts, but I will focus on the bad parts if that's alright in order to provide constructive criticism:
- The writing needs a lot more editing to tighten up the prose
- The lack of organization or continuity.  I can never really anticipate where the text will go next as I read
- Visual design issues, particularly: weird navigation buttons, ugly font, non-fixed-width code in text, the  distracting background colors, font color that almost matches the background, and the wildly varying font sizes in the code blocks
- Long stretches of uninterrupted text without any illustrative code fragments or examples (such as Section 4: The Main Road): "show, don't tell"
- The code blocks are images
- There is no sense of "reward" or "payoff" at the end of each section.  It's very underwhelming

Some concrete advice for how you can improve:
- Buy [this book](http://www.amazon.com/On-Writing-Well-Classic-Nonfiction/dp/0060891548) to improve writing style.  I can't recommend it enough for improving technical writing (or even writing in general)
- Read as much of the "Haskell programming from first principles" book as possible and compare your work side-by-side with it.  That book is a great example of well-done technical writing
- For improving visual design, try rendering your book using LaTeX and compare and contrast your visual design with the LaTex defaults
- For each section (and the entire book) set clear expectations at the beginning for what the reader will get out of it and deliver on that promise

But the most important skill of all to cultivate is to be **extremely critical** of your own work.  You should be your own worst critic if you really want to produce something exceptional.  Also, the more you edit and polish your work before sharing with others the higher quality the feedback you will receive, which leads to a virtuous cycle.

**Comment by GetContented** [comment]
Lots of good points, Gabriel. Thanks! We're well aware of most of them. 

All the feedback from beginners we've received has been them saying that they've really enjoyed it, so there you go! :)

**Comment by Gabriella439** [comment]
Alright, then I will go ahead and close this, then, but if you would like me to revisit this later then reopen the issue.
